[general]
enable_bucket = true
bucket_reso_steps = 64
caption_extension = ".txt"
shuffle_caption = false
keep_tokens = 1

[[datasets]]
resolution = 1024
batch_size = 2

  [[datasets.subsets]]
  image_dir = "/root/autodl-tmp/anima-train/data"
  num_repeats = 6
